export interface Exercise {
  name: string;
  tags: ExerciseTag[];
  favorite: boolean;
  isPowerlifting: boolean;
  bodyweight: boolean;
  repType: 'reps' | 'time';
  warmupProtocol?: { exo?: string; weight: string; reps: number; weightUnit: 'kg' | '%' }[];
  description?: {
    title: string;
    content: string;
  };
  category: ExerciseCategory[];
  strengthType?: 'strength' | 'hypertrophy' | 'power' | 'skill' | 'endurance';
  unilateral?: boolean;
  equipment?: 'barbell' | 'rings' | 'bodyweight' | 'dumbbell' | 'machine';
}

export const EXERCISE_TAGS = [
  'Legs',
  'Quads',
  'Glutes',
  'Compound',
  'Powerlifting',
  'Back',
  'Hamstrings',
  'Chest',
  'Triceps',
  'Shoulders',
  'Core',
  'Lats',
  'Biceps',
  'Pulling',
  'Abs',
  'Pushing',
  'Grip',
  'Isometric',
  'Balance',
  'Hip Flexors',
  'Obliques',
  'Calves',
  'Isolation',
  'Plyometric',
  'Traps',
  'Adductors',
  'Cardio',
  'Full Body',
  'Stretching',
] as const;

export type ExerciseCategory =
  | 'push_vertical'
  | 'push_horizontal'
  | 'pull_vertical'
  | 'pull_horizontal'
  | 'squat'
  | 'hinge'
  | 'core'
  | 'skill'
  | 'mobility'
  | 'cardio'
  | 'conditioning';

export type ExerciseTag = (typeof EXERCISE_TAGS)[number];

export const defaultWarmupProtocol = [
  { weight: '30', reps: 10, weightUnit: '%' },
  { weight: '60', reps: 5, weightUnit: '%' },
  { weight: '85', reps: 2, weightUnit: '%' },
];

export const EXERCISES: Exercise[] = [
  // ===== POWERLIFTING =====
  {
    name: 'Squat',
    tags: ['Legs', 'Quads', 'Glutes', 'Compound', 'Powerlifting'],
    favorite: true,
    isPowerlifting: true,
    bodyweight: false,
    repType: 'reps',
    category: ['squat', 'core'],
    strengthType: 'strength',
    equipment: 'barbell',
    warmupProtocol: [
      { weight: '20', reps: 10, weightUnit: 'kg' },
      { weight: '60', reps: 5, weightUnit: '%' },
      { weight: '85', reps: 2, weightUnit: '%' },
    ],
  },
  {
    name: 'Deadlift',
    tags: ['Back', 'Legs', 'Hamstrings', 'Glutes', 'Compound', 'Powerlifting'],
    favorite: true,
    isPowerlifting: true,
    bodyweight: false,
    repType: 'reps',
    category: ['hinge', 'core'],
    strengthType: 'strength',
    equipment: 'barbell',
    warmupProtocol: [
      { weight: '20', reps: 10, weightUnit: 'kg' },
      { weight: '40', reps: 8, weightUnit: '%' },
      { weight: '70', reps: 4, weightUnit: '%' },
      { weight: '90', reps: 1, weightUnit: '%' },
    ],
  },
  {
    name: 'Trap bar Deadlift',
    tags: ['Back', 'Legs', 'Quads', 'Glutes', 'Compound', 'Powerlifting'],
    favorite: true,
    isPowerlifting: true,
    bodyweight: false,
    repType: 'reps',
    category: ['hinge', 'squat', 'core'],
    strengthType: 'strength',
    equipment: 'barbell',
    warmupProtocol: [
      { weight: '20', reps: 10, weightUnit: 'kg' },
      { weight: '40', reps: 8, weightUnit: '%' },
      { weight: '70', reps: 4, weightUnit: '%' },
      { weight: '90', reps: 1, weightUnit: '%' },
    ],
  },
  {
    name: 'Bench Press',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Powerlifting'],
    favorite: true,
    isPowerlifting: true,
    bodyweight: false,
    repType: 'reps',
    category: ['push_horizontal'],
    strengthType: 'strength',
    equipment: 'barbell',
  },
  // ===== CALISTHÉNIE - PULLING =====
  {
    name: 'Pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_vertical'],
    strengthType: 'strength',
    equipment: 'bodyweight',
    description: {
      title: 'Mindset focus : change brain instructions',
      content: `
      <ul class="list-disc pl-4 space-y-1">
        <li>Not pull you up : Push your chest up the ceiling</li>
        <li>Driving your elbows down and back</li>
        <li>Active scapula depress / shoulders down</li>
      </ul>  `,
    },
  },
  {
    name: 'Chin up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_vertical'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Wide grip pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_vertical'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Close grip pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_vertical'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Hammer pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_vertical'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'L-sit pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Core', 'Abs', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_vertical', 'core'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Archer pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_vertical'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Typewriter pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_vertical'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'One arm pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_vertical'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Eccentric OAP',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_vertical'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Assisted OAP',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_vertical'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Muscle up',
    tags: ['Back', 'Lats', 'Triceps', 'Chest', 'Compound', 'Pulling', 'Pushing'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_vertical', 'push_vertical'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Ring muscle up',
    tags: ['Back', 'Lats', 'Triceps', 'Chest', 'Compound', 'Pulling', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_vertical', 'push_vertical'],
    strengthType: 'skill',
    equipment: 'rings',
  },
  {
    name: 'Body rows',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_horizontal'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Ring rows',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_horizontal'],
    strengthType: 'strength',
    equipment: 'rings',
  },
  {
    name: 'Australian pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['pull_horizontal'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Front lever',
    tags: ['Back', 'Lats', 'Core', 'Abs', 'Isometric', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['skill', 'pull_vertical', 'core'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Front lever pull',
    tags: ['Back', 'Lats', 'Biceps', 'Core', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['skill', 'pull_vertical', 'core'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Back lever',
    tags: ['Back', 'Lats', 'Biceps', 'Core', 'Isometric', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['skill', 'pull_vertical', 'core'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Dead hang hold',
    tags: ['Back', 'Lats', 'Grip', 'Isometric', 'Pulling'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['pull_vertical'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Active hang hold',
    tags: ['Back', 'Lats', 'Biceps', 'Grip', 'Isometric', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['pull_vertical'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'One arm hang hold',
    tags: ['Back', 'Lats', 'Grip', 'Isometric', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['pull_vertical'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },

  // ===== CALISTHÉNIE - PUSHING =====
  {
    name: 'Push up',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['push_horizontal'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Diamond push up',
    tags: ['Chest', 'Triceps', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['push_horizontal'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Wide push up',
    tags: ['Chest', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['push_horizontal'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Archer push up',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['push_horizontal'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Pseudo planche push up',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['push_horizontal', 'skill'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Planche lean hold',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['skill', 'push_horizontal'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Tuck planche hold',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Core', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['skill', 'push_horizontal'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Tuck planche push up',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Core', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['skill', 'push_horizontal'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Pike push up',
    tags: ['Shoulders', 'Triceps', 'Core', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['push_vertical'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Handstand push up',
    tags: ['Shoulders', 'Triceps', 'Core', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['push_vertical', 'skill'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Handstand kicks',
    tags: ['Shoulders', 'Core', 'Balance', 'Pushing'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['skill', 'push_vertical'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Handstand',
    tags: ['Shoulders', 'Core', 'Balance', 'Pushing'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['skill', 'push_vertical'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Dips',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['push_vertical', 'push_horizontal'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Bar dips',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['push_vertical', 'push_horizontal'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Ring dips',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['push_vertical', 'push_horizontal'],
    strengthType: 'strength',
    equipment: 'rings',
  },
  {
    name: 'Ring support hold',
    tags: ['Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['core', 'push_horizontal'],
    strengthType: 'strength',
    equipment: 'rings',
  },
  {
    name: 'L-sit dips',
    tags: ['Chest', 'Triceps', 'Core', 'Abs', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['push_vertical', 'push_horizontal', 'core'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Korean dips',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['push_vertical', 'skill'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Planche',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Core', 'Isometric', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['skill', 'push_horizontal', 'core'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Handstand hold',
    tags: ['Shoulders', 'Core', 'Balance', 'Isometric', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['skill', 'push_vertical'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },

  // ===== CALISTHÉNIE - CORE =====
  {
    name: 'L-sit hold',
    tags: ['Core', 'Abs', 'Triceps', 'Isometric'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['core', 'skill'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'V-sit hold',
    tags: ['Core', 'Abs', 'Isometric'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['core', 'skill'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Hanging leg raise',
    tags: ['Core', 'Abs', 'Hip Flexors', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['core', 'pull_vertical'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Toes to bar',
    tags: ['Core', 'Abs', 'Back', 'Hip Flexors', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['core', 'pull_vertical'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Dragon flag',
    tags: ['Core', 'Abs', 'Hip Flexors', 'Isometric'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['core', 'skill'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Human flag',
    tags: ['Core', 'Abs', 'Shoulders', 'Isometric'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['skill', 'core'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Ab wheel rollout',
    tags: ['Core', 'Abs', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['core', 'push_horizontal'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Plank',
    tags: ['Core', 'Abs', 'Isometric'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['core'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Side plank',
    tags: ['Core', 'Abs', 'Obliques', 'Isometric'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['core'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Hollow body hold',
    tags: ['Core', 'Abs', 'Isometric'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['core'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Arch hold',
    tags: ['Core', 'Back', 'Glutes', 'Isometric'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
    category: ['core'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },

  // ===== CALISTHÉNIE - LEGS =====
  {
    name: 'Pistol squat',
    tags: ['Legs', 'Quads', 'Glutes', 'Balance', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['squat', 'skill'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Shrimp squat',
    tags: ['Legs', 'Quads', 'Glutes', 'Balance', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['squat', 'skill'],
    strengthType: 'skill',
    equipment: 'bodyweight',
  },
  {
    name: 'Sissy squat',
    tags: ['Legs', 'Quads', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['squat'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Jump squat',
    tags: ['Legs', 'Quads', 'Glutes', 'Plyometric', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['squat', 'conditioning'],
    strengthType: 'power',
    equipment: 'bodyweight',
  },
  {
    name: 'Bulgarian split squat',
    tags: ['Legs', 'Quads', 'Glutes', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['squat'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Lunges',
    tags: ['Legs', 'Quads', 'Glutes', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['squat'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Reverse lunges',
    tags: ['Legs', 'Quads', 'Glutes', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['squat'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Walking lunges',
    tags: ['Legs', 'Quads', 'Glutes', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['squat'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Calf raises',
    tags: ['Legs', 'Calves', 'Isolation'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['conditioning'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Single leg calf raise',
    tags: ['Legs', 'Calves', 'Isolation'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['conditioning'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Nordic curl',
    tags: ['Legs', 'Hamstrings', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['hinge', 'core'],
    strengthType: 'strength',
    equipment: 'bodyweight',
  },
  {
    name: 'Glute bridge',
    tags: ['Legs', 'Glutes', 'Hamstrings', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['hinge', 'core'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Single leg glute bridge',
    tags: ['Legs', 'Glutes', 'Hamstrings', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['hinge', 'core'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Hip thrust',
    tags: ['Legs', 'Glutes', 'Hamstrings', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['hinge', 'core'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },

  // ===== MUSCULATION CLASSIQUE - UPPER BODY PUSHING =====
  {
    name: 'Incline bench press',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_horizontal'],
    strengthType: 'hypertrophy',
    equipment: 'barbell',
  },
  {
    name: 'Decline bench press',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_horizontal'],
    strengthType: 'hypertrophy',
    equipment: 'barbell',
  },
  {
    name: 'Dumbbell bench press',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_horizontal'],
    strengthType: 'hypertrophy',
    equipment: 'dumbbell',
  },
  {
    name: 'Incline dumbbell press',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_horizontal'],
    strengthType: 'hypertrophy',
    equipment: 'dumbbell',
  },
  {
    name: 'Dumbbell flyes',
    tags: ['Chest', 'Isolation', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_horizontal'],
    strengthType: 'hypertrophy',
    equipment: 'dumbbell',
  },
  {
    name: 'Cable flyes',
    tags: ['Chest', 'Isolation', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_horizontal'],
    strengthType: 'hypertrophy',
    equipment: 'dumbbell',
  },
  {
    name: 'Overhead press',
    tags: ['Shoulders', 'Triceps', 'Core', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_vertical', 'core'],
    strengthType: 'strength',
    equipment: 'barbell',
  },
  {
    name: 'Overhead press dumbell',
    tags: ['Shoulders', 'Triceps', 'Core', 'Compound', 'Pushing'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_vertical', 'core'],
    strengthType: 'strength',
    equipment: 'dumbbell',
    description: {
      title: 'Focus : Stabilité scapulaire & Force de poussée verticale.',
      content: ` <ul class="list-disc pl-4 space-y-1">
        <li><strong>Placement :</strong> Haltères aux épaules, coudes orientés à 45° vers l'avant (pas sur les côtés).</li>
        <li><strong>Exécution :</strong> Presse verticalement en gardant les abdos contractés pour ne pas cambrer.</li>
        <li><strong>Skill Transfer :</strong> Travaille la phase de verrouillage utile pour tes <strong>HSPU</strong>.</li>
      </ul>`,
    },
  },
  {
    name: 'Overhead press dumbell - standing',
    tags: ['Shoulders', 'Triceps', 'Compound', 'Pushing'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_vertical', 'core'],
    strengthType: 'strength',
    equipment: 'dumbbell',
    description: {
      title: 'Focus : Stabilité scapulaire & Force de poussée verticale.',
      content: ` <ul class="list-disc pl-4 space-y-1">
        <li><strong>Placement :</strong> Haltères aux épaules, coudes orientés à 45° vers l'avant (pas sur les côtés).</li>
        <li><strong>Exécution :</strong> Presse verticalement en gardant les abdos contractés pour ne pas cambrer.</li>
        <li><strong>Skill Transfer :</strong> Travaille la phase de verrouillage utile pour tes <strong>HSPU</strong>.</li>
      </ul>`,
    },
  },
  {
    name: 'Lateral raises',
    tags: ['Shoulders', 'Isolation', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_vertical'],
    strengthType: 'hypertrophy',
    equipment: 'dumbbell',
  },
  {
    name: 'Front raises',
    tags: ['Shoulders', 'Isolation', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_vertical'],
    strengthType: 'hypertrophy',
    equipment: 'dumbbell',
  },
  {
    name: 'Rear delt flyes',
    tags: ['Shoulders', 'Back', 'Isolation', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['pull_horizontal'],
    strengthType: 'hypertrophy',
    equipment: 'dumbbell',
  },
  {
    name: 'Tricep dips',
    tags: ['Triceps', 'Shoulders', 'Isolation', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_vertical'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Tricep extensions',
    tags: ['Triceps', 'Isolation', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_horizontal'],
    strengthType: 'hypertrophy',
    equipment: 'dumbbell',
  },
  {
    name: 'Overhead tricep extension',
    tags: ['Triceps', 'Isolation', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_vertical'],
    strengthType: 'hypertrophy',
    equipment: 'dumbbell',
  },
  {
    name: 'Cable tricep pushdown',
    tags: ['Triceps', 'Isolation', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_vertical'],
    strengthType: 'hypertrophy',
    equipment: 'dumbbell',
  },
  {
    name: 'Close grip bench press',
    tags: ['Triceps', 'Chest', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['push_horizontal'],
    strengthType: 'strength',
    equipment: 'barbell',
  },

  // ===== MUSCULATION CLASSIQUE - UPPER BODY PULLING =====
  {
    name: 'Barbell row',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: true,
    isPowerlifting: true,
    bodyweight: false,
    repType: 'reps',
    category: ['pull_horizontal', 'core'],
    strengthType: 'strength',
    equipment: 'barbell',
    description: {
      title: 'Focus : Épaisseur du dos & Transfert Muscle-up.',
      content: `
      <ul class="list-disc pl-4 space-y-1">
        <li><strong>Placement :</strong> Buste à 45°, dos plat, genoux déverrouillés.</li>
        <li><strong>Exécution :</strong> Tire la barre vers le nombril en resserrant volontairement les omoplates.</li>
        <li><strong>Astuce :</strong> Imagine que tu veux couder quelqu'un derrière toi pour engager les dorsaux.</li>
      </ul>
  
  `,
    },
  },
  {
    name: 'T-bar row',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['pull_horizontal', 'core'],
    strengthType: 'hypertrophy',
    equipment: 'barbell',
  },
  {
    name: 'Face Pull',
    tags: ['Shoulders', 'Back', 'Isolation', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['pull_horizontal'],
    strengthType: 'hypertrophy',
    equipment: 'dumbbell',
  },
  {
    name: 'Bicep curls',
    tags: ['Biceps', 'Isolation', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['pull_vertical'],
    strengthType: 'hypertrophy',
    equipment: 'dumbbell',
  },
  {
    name: 'Hammer curls',
    tags: ['Biceps', 'Isolation', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['pull_vertical'],
    strengthType: 'hypertrophy',
    equipment: 'dumbbell',
  },
  {
    name: 'Jefferson curls',
    tags: ['Back', 'Legs', 'Hamstrings', 'Glutes', 'Compound', 'Pulling', 'Stretching'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['pull_vertical'],
    strengthType: 'hypertrophy',
    equipment: 'dumbbell',
  },
  {
    name: 'Shrugs',
    tags: ['Back', 'Traps', 'Isolation', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['pull_vertical'],
    strengthType: 'hypertrophy',
    equipment: 'barbell',
  },
  {
    name: 'Upright row',
    tags: ['Shoulders', 'Traps', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['pull_vertical', 'push_vertical'],
    strengthType: 'hypertrophy',
    equipment: 'barbell',
  },

  // ===== MUSCULATION CLASSIQUE - LOWER BODY =====
  {
    name: 'Front squat',
    tags: ['Legs', 'Quads', 'Glutes', 'Core', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    category: ['squat', 'core'],
    strengthType: 'strength',
    equipment: 'barbell',
  },
  // ===== MUSCULATION CLASSIQUE - CORE =====
  {
    name: 'Russian twist',
    tags: ['Core', 'Abs', 'Obliques'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['core'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Crunches',
    tags: ['Core', 'Abs', 'Isolation'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['core'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Sit ups',
    tags: ['Core', 'Abs', 'Hip Flexors'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['core'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Bicycle crunches',
    tags: ['Core', 'Abs', 'Obliques', 'Hip Flexors'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['core'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Bike',
    tags: ['Legs', 'Cardio', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'time',
    category: ['cardio', 'conditioning'],
    strengthType: 'endurance',
    equipment: 'machine',
  },
  {
    name: 'Mountain climbers',
    tags: ['Core', 'Abs', 'Cardio', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['conditioning', 'core'],
    strengthType: 'hypertrophy',
    equipment: 'bodyweight',
  },
  {
    name: 'Burpees',
    tags: ['Core', 'Full Body', 'Cardio', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
    category: ['conditioning', 'push_horizontal', 'squat'],
    strengthType: 'power',
    equipment: 'bodyweight',
  },
].map(
  (exercise) =>
    ({
      ...exercise,
      warmupProtocol: exercise.warmupProtocol ? exercise.warmupProtocol : exercise.bodyweight ? undefined : defaultWarmupProtocol,
    }) as Exercise
);

export type ExerciseName = Exercise['name'];
