export interface Exercise {
  name: string;
  tags: ExerciseTag[];
  favorite: boolean;
  isPowerlifting: boolean;
  bodyweight: boolean;
  repType: 'reps' | 'time';
  warmupProtocol?: { exo?: string; weight: string; reps: number; weightUnit: 'kg' | '%' }[];
  description?: string;
}

export const EXERCISE_TAGS = [
  'Legs',
  'Quads',
  'Glutes',
  'Compound',
  'Powerlifting',
  'Back',
  'Hamstrings',
  'Chest',
  'Triceps',
  'Shoulders',
  'Core',
  'Lats',
  'Biceps',
  'Pulling',
  'Abs',
  'Pushing',
  'Grip',
  'Isometric',
  'Balance',
  'Hip Flexors',
  'Obliques',
  'Calves',
  'Isolation',
  'Plyometric',
  'Traps',
  'Adductors',
  'Cardio',
  'Full Body',
] as const;

export type ExerciseTag = (typeof EXERCISE_TAGS)[number];

export const defaultWarmupProtocol = [
  { weight: '30', reps: 10, weightUnit: '%' },
  { weight: '60', reps: 5, weightUnit: '%' },
  { weight: '85', reps: 2, weightUnit: '%' },
];

export const EXERCISES: Exercise[] = [
  // ===== POWERLIFTING =====
  {
    name: 'Squat',
    tags: ['Legs', 'Quads', 'Glutes', 'Compound', 'Powerlifting'],
    favorite: true,
    isPowerlifting: true,
    bodyweight: false,
    repType: 'reps',
    warmupProtocol: [
      { weight: '20', reps: 10, weightUnit: 'kg' },
      { weight: '60', reps: 5, weightUnit: '%' },
      { weight: '85', reps: 2, weightUnit: '%' },
    ],
  },
  {
    name: 'Deadlift',
    tags: ['Back', 'Legs', 'Hamstrings', 'Glutes', 'Compound', 'Powerlifting'],
    favorite: true,
    isPowerlifting: true,
    bodyweight: false,
    repType: 'reps',
    warmupProtocol: [
      { weight: '20', reps: 10, weightUnit: 'kg' },
      { weight: '40', reps: 8, weightUnit: '%' },
      { weight: '70', reps: 4, weightUnit: '%' },
      { weight: '90', reps: 1, weightUnit: '%' },
    ],
  },
  {
    name: 'Bench Press',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Powerlifting'],
    favorite: true,
    isPowerlifting: true,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Overhead Press',
    tags: ['Shoulders', 'Triceps', 'Core', 'Compound', 'Powerlifting'],
    favorite: false,
    isPowerlifting: true,
    bodyweight: false,
    repType: 'reps',
  },

  // ===== CALISTHÉNIE - PULLING =====
  {
    name: 'Pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Chin up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Wide grip pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Close grip pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Hammer pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'L-sit pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Core', 'Abs', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Archer pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Typewriter pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Muscle up',
    tags: ['Back', 'Lats', 'Triceps', 'Chest', 'Compound', 'Pulling', 'Pushing'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Ring muscle up',
    tags: ['Back', 'Lats', 'Triceps', 'Chest', 'Compound', 'Pulling', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Body rows',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Ring rows',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Horizontal row',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Inverted row',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Australian pull up',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Front lever',
    tags: ['Back', 'Lats', 'Core', 'Abs', 'Isometric', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
  },
  {
    name: 'Front lever pull',
    tags: ['Back', 'Lats', 'Biceps', 'Core', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Back lever',
    tags: ['Back', 'Lats', 'Biceps', 'Core', 'Isometric', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
  },
  {
    name: 'Dead hang hold',
    tags: ['Back', 'Lats', 'Grip', 'Isometric', 'Pulling'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
  },
  {
    name: 'Active hang hold',
    tags: ['Back', 'Lats', 'Biceps', 'Grip', 'Isometric', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
  },
  {
    name: 'One arm hang hold',
    tags: ['Back', 'Lats', 'Grip', 'Isometric', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
  },

  // ===== CALISTHÉNIE - PUSHING =====
  {
    name: 'Push up',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Diamond push up',
    tags: ['Chest', 'Triceps', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Wide push up',
    tags: ['Chest', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Archer push up',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Pseudo planche push up',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Planche push up',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Core', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Hindu push up',
    tags: ['Chest', 'Shoulders', 'Back', 'Core', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Pike push up',
    tags: ['Shoulders', 'Triceps', 'Core', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Handstand push up',
    tags: ['Shoulders', 'Triceps', 'Core', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Handstand kicks',
    tags: ['Shoulders', 'Core', 'Balance', 'Pushing'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Dips',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Bar dips',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Ring dips',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'L-sit dips',
    tags: ['Chest', 'Triceps', 'Core', 'Abs', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Korean dips',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Planche',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Core', 'Isometric', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
  },
  {
    name: 'Handstand hold',
    tags: ['Shoulders', 'Core', 'Balance', 'Isometric', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'time',
  },

  // ===== CALISTHÉNIE - CORE =====
  { name: 'L-sit hold', tags: ['Core', 'Abs', 'Triceps', 'Isometric'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'time' },
  { name: 'V-sit hold', tags: ['Core', 'Abs', 'Isometric'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'time' },
  {
    name: 'Hanging leg raise',
    tags: ['Core', 'Abs', 'Hip Flexors', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Toes to bar',
    tags: ['Core', 'Abs', 'Back', 'Hip Flexors', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Knee to elbow',
    tags: ['Core', 'Abs', 'Hip Flexors', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Dragon flag',
    tags: ['Core', 'Abs', 'Hip Flexors', 'Isometric'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  { name: 'Human flag', tags: ['Core', 'Abs', 'Shoulders', 'Isometric'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'time' },
  { name: 'Ab wheel rollout', tags: ['Core', 'Abs', 'Compound'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'reps' },
  { name: 'Plank', tags: ['Core', 'Abs', 'Isometric'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'time' },
  { name: 'Side plank', tags: ['Core', 'Abs', 'Obliques', 'Isometric'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'time' },
  { name: 'Hollow body hold', tags: ['Core', 'Abs', 'Isometric'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'time' },
  { name: 'Arch hold', tags: ['Core', 'Back', 'Glutes', 'Isometric'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'time' },

  // ===== CALISTHÉNIE - LEGS =====
  {
    name: 'Pistol squat',
    tags: ['Legs', 'Quads', 'Glutes', 'Balance', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Shrimp squat',
    tags: ['Legs', 'Quads', 'Glutes', 'Balance', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  { name: 'Sissy squat', tags: ['Legs', 'Quads', 'Compound'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'reps' },
  {
    name: 'Jump squat',
    tags: ['Legs', 'Quads', 'Glutes', 'Plyometric', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Bulgarian split squat',
    tags: ['Legs', 'Quads', 'Glutes', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  { name: 'Lunges', tags: ['Legs', 'Quads', 'Glutes', 'Compound'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'reps' },
  {
    name: 'Reverse lunges',
    tags: ['Legs', 'Quads', 'Glutes', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Walking lunges',
    tags: ['Legs', 'Quads', 'Glutes', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  { name: 'Calf raises', tags: ['Legs', 'Calves', 'Isolation'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'reps' },
  { name: 'Single leg calf raise', tags: ['Legs', 'Calves', 'Isolation'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'reps' },
  { name: 'Nordic curl', tags: ['Legs', 'Hamstrings', 'Compound'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'reps' },
  {
    name: 'Glute bridge',
    tags: ['Legs', 'Glutes', 'Hamstrings', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Single leg glute bridge',
    tags: ['Legs', 'Glutes', 'Hamstrings', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Hip thrust',
    tags: ['Legs', 'Glutes', 'Hamstrings', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },

  // ===== MUSCULATION CLASSIQUE - UPPER BODY PUSHING =====
  {
    name: 'Incline bench press',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Decline bench press',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Dumbbell bench press',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Incline dumbbell press',
    tags: ['Chest', 'Triceps', 'Shoulders', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  { name: 'Dumbbell flyes', tags: ['Chest', 'Isolation', 'Pushing'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  { name: 'Cable flyes', tags: ['Chest', 'Isolation', 'Pushing'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  {
    name: 'Overhead press',
    tags: ['Shoulders', 'Triceps', 'Core', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Overhead press dumbell',
    tags: ['Shoulders', 'Triceps', 'Core', 'Compound', 'Pushing'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    description: `<div class="space-y-2">
      <p class="font-medium text-primary">Focus : Stabilité scapulaire & Force de poussée verticale.</p>
      <ul class="list-disc pl-4 text-sm space-y-1">
        <li><strong>Placement :</strong> Haltères aux épaules, coudes orientés à 45° vers l'avant (pas sur les côtés).</li>
        <li><strong>Exécution :</strong> Presse verticalement en gardant les abdos contractés pour ne pas cambrer.</li>
        <li><strong>Skill Transfer :</strong> Travaille la phase de verrouillage utile pour tes <strong>HSPU</strong>.</li>
      </ul>
    </div>
  `,
  },
  {
    name: 'Overhead press dumbell - standing',
    tags: ['Shoulders', 'Triceps', 'Compound', 'Pushing'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    description: `<div class="space-y-2">
      <p class="font-medium text-primary">Focus : Stabilité scapulaire & Force de poussée verticale.</p>
      <ul class="list-disc pl-4 text-sm space-y-1">
        <li><strong>Placement :</strong> Haltères aux épaules, coudes orientés à 45° vers l'avant (pas sur les côtés).</li>
        <li><strong>Exécution :</strong> Presse verticalement en gardant les abdos contractés pour ne pas cambrer.</li>
        <li><strong>Skill Transfer :</strong> Travaille la phase de verrouillage utile pour tes <strong>HSPU</strong>.</li>
      </ul>
    </div>
  `,
  },
  {
    name: 'Dumbbell shoulder press',
    tags: ['Shoulders', 'Triceps', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  { name: 'Lateral raises', tags: ['Shoulders', 'Isolation', 'Pushing'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  { name: 'Front raises', tags: ['Shoulders', 'Isolation', 'Pushing'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  {
    name: 'Rear delt flyes',
    tags: ['Shoulders', 'Back', 'Isolation', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Tricep dips',
    tags: ['Triceps', 'Shoulders', 'Isolation', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Tricep extensions',
    tags: ['Triceps', 'Isolation', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Overhead tricep extension',
    tags: ['Triceps', 'Isolation', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Cable tricep pushdown',
    tags: ['Triceps', 'Isolation', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Close grip bench press',
    tags: ['Triceps', 'Chest', 'Compound', 'Pushing'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },

  // ===== MUSCULATION CLASSIQUE - UPPER BODY PULLING =====
  {
    name: 'Barbell row',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: true,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
    description: `
    <div class="space-y-2">
      <p class="font-medium text-primary">Focus : Épaisseur du dos & Transfert Muscle-up.</p>
      <ul class="list-disc pl-4 text-sm space-y-1">
        <li><strong>Placement :</strong> Buste à 45°, dos plat, genoux déverrouillés.</li>
        <li><strong>Exécution :</strong> Tire la barre vers le nombril en resserrant volontairement les omoplates.</li>
        <li><strong>Astuce :</strong> Imagine que tu veux couder quelqu'un derrière toi pour engager les dorsaux.</li>
      </ul>
    </div>
  `,
  },
  {
    name: 'T-bar row',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Cable row',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Seated cable row',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'One arm dumbbell row',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Chest supported row',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Lat pulldown',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Wide grip lat pulldown',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Close grip lat pulldown',
    tags: ['Back', 'Lats', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Cable pullover',
    tags: ['Back', 'Lats', 'Chest', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Face pull',
    tags: ['Shoulders', 'Back', 'Isolation', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  { name: 'Bicep curls', tags: ['Biceps', 'Isolation', 'Pulling'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  { name: 'Hammer curls', tags: ['Biceps', 'Isolation', 'Pulling'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  { name: 'Cable bicep curl', tags: ['Biceps', 'Isolation', 'Pulling'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  { name: 'Preacher curl', tags: ['Biceps', 'Isolation', 'Pulling'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  {
    name: 'Concentration curl',
    tags: ['Biceps', 'Isolation', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  { name: 'Shrugs', tags: ['Back', 'Traps', 'Isolation', 'Pulling'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  {
    name: 'Upright row',
    tags: ['Shoulders', 'Traps', 'Biceps', 'Compound', 'Pulling'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },

  // ===== MUSCULATION CLASSIQUE - LOWER BODY =====
  {
    name: 'Front squat',
    tags: ['Legs', 'Quads', 'Glutes', 'Core', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  { name: 'Hack squat', tags: ['Legs', 'Quads', 'Glutes', 'Compound'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  { name: 'Leg press', tags: ['Legs', 'Quads', 'Glutes', 'Compound'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  { name: 'Leg extension', tags: ['Legs', 'Quads', 'Isolation'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  {
    name: 'Romanian deadlift',
    tags: ['Legs', 'Hamstrings', 'Glutes', 'Back', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Stiff leg deadlift',
    tags: ['Legs', 'Hamstrings', 'Glutes', 'Back', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  {
    name: 'Good morning',
    tags: ['Legs', 'Hamstrings', 'Glutes', 'Back', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  { name: 'Leg curl', tags: ['Legs', 'Hamstrings', 'Isolation'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  { name: 'Lying leg curl', tags: ['Legs', 'Hamstrings', 'Isolation'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  { name: 'Standing calf raise', tags: ['Legs', 'Calves', 'Isolation'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  { name: 'Seated calf raise', tags: ['Legs', 'Calves', 'Isolation'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  {
    name: 'Lateral lunges',
    tags: ['Legs', 'Quads', 'Glutes', 'Adductors', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: false,
    repType: 'reps',
  },
  { name: 'Step ups', tags: ['Legs', 'Quads', 'Glutes', 'Compound'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  { name: 'Leg abduction', tags: ['Legs', 'Glutes', 'Isolation'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  { name: 'Leg adduction', tags: ['Legs', 'Adductors', 'Isolation'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },

  // ===== MUSCULATION CLASSIQUE - CORE =====
  { name: 'Cable crunch', tags: ['Core', 'Abs', 'Isolation'], favorite: false, isPowerlifting: false, bodyweight: false, repType: 'reps' },
  { name: 'Russian twist', tags: ['Core', 'Abs', 'Obliques'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'reps' },
  { name: 'Crunches', tags: ['Core', 'Abs', 'Isolation'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'reps' },
  { name: 'Sit ups', tags: ['Core', 'Abs', 'Hip Flexors'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'reps' },
  {
    name: 'Bicycle crunches',
    tags: ['Core', 'Abs', 'Obliques', 'Hip Flexors'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  {
    name: 'Mountain climbers',
    tags: ['Core', 'Abs', 'Cardio', 'Compound'],
    favorite: false,
    isPowerlifting: false,
    bodyweight: true,
    repType: 'reps',
  },
  { name: 'Burpees', tags: ['Core', 'Full Body', 'Cardio', 'Compound'], favorite: false, isPowerlifting: false, bodyweight: true, repType: 'reps' },
].map(
  (exercise) =>
    ({
      ...exercise,
      warmupProtocol: exercise.warmupProtocol ? exercise.warmupProtocol : exercise.bodyweight ? undefined : defaultWarmupProtocol,
    }) as Exercise
);

export type ExerciseName = Exercise['name'];
